import { StyleSheet } from 'react-native';
export const blue = '#3267E3';
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F7F9FC' }, safe: { flex: 1 }, app: { flex: 1, width: '100%', maxWidth: 560, alignSelf: 'center', backgroundColor: '#FFFFFF' },
  brand: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 26, paddingTop: 22, paddingBottom: 36, gap: 9 }, logo: { width: 30, height: 30, borderRadius: 9, backgroundColor: blue, justifyContent: 'center', alignItems: 'center' }, brandText: { fontSize: 21, fontWeight: '700', letterSpacing: -0.7, color: '#23324C' }, cloudButton: { flexDirection: 'row', alignItems: 'center', gap: 5, marginLeft: 'auto', minHeight: 34, paddingHorizontal: 9, borderRadius: 9, backgroundColor: '#F0F5FF' }, cloudText: { fontSize: 9, letterSpacing: 0.8, color: blue, fontWeight: '700' },
  heading: { paddingHorizontal: 26, paddingBottom: 31 }, titleRow: { flexDirection: 'row', alignItems: 'center', gap: 12 }, headingText: { fontSize: 40, fontWeight: '700', color: '#1D2B43', letterSpacing: -1.5 }, count: { minWidth: 29, paddingHorizontal: 8, height: 28, borderRadius: 10, backgroundColor: '#EFF3FA', alignItems: 'center', justifyContent: 'center' }, countText: { color: '#71819B', fontSize: 13, fontWeight: '600' }, subtitle: { fontSize: 15, color: '#8490A2', marginTop: 9 },
  section: { paddingHorizontal: 26, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }, sectionLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 1.5, color: '#8C97A8' }, hint: { flexDirection: 'row', alignItems: 'center', gap: 5 }, hintText: { fontSize: 10, color: '#929BAB' }, list: { flex: 1 }, listContent: { paddingHorizontal: 22, paddingTop: 3, paddingBottom: 115 }, emptyList: { flexGrow: 1 },
  card: { flexDirection: 'row', alignItems: 'center', minHeight: 88, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8ECF2', borderRadius: 18, paddingLeft: 18, paddingRight: 7, paddingVertical: 14, marginBottom: 12 }, firstCard: { backgroundColor: '#F2F6FF', borderColor: '#CFDEFD', minHeight: 100 }, dragCard: { borderColor: blue, elevation: 8, shadowColor: blue, shadowOpacity: 0.15, shadowRadius: 12, shadowOffset: { width: 0, height: 5 } }, rank: { fontSize: 27, fontWeight: '600', color: '#9AA6B8', minWidth: 41, fontVariant: ['tabular-nums'] }, taskText: { flex: 1, paddingRight: 4 }, nextLabel: { fontSize: 9, letterSpacing: 1.4, fontWeight: '700', color: blue, marginBottom: 6 }, taskTitle: { fontSize: 16, fontWeight: '500', lineHeight: 23, color: '#2B3950' }, touch: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, checkbox: { width: 22, height: 22, borderRadius: 8, borderWidth: 1.5, borderColor: '#C5CFDF', backgroundColor: '#FFFFFF' }, handle: { minWidth: 36, minHeight: 48, alignItems: 'center', justifyContent: 'center' },
  footerNote: { alignItems: 'center', paddingTop: 30 }, smallLine: { width: 27, height: 2, backgroundColor: '#E5EBF3', marginBottom: 16 }, note: { fontSize: 12, color: '#9AA4B3' }, fabWrap: { position: 'absolute', bottom: 100, alignSelf: 'center' }, fab: { flexDirection: 'row', gap: 9, backgroundColor: blue, paddingHorizontal: 25, height: 56, borderRadius: 19, alignItems: 'center', shadowColor: blue, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.24, shadowRadius: 13, elevation: 5 }, fabText: { fontSize: 15, fontWeight: '600', color: '#FFFFFF' },
  nav: { flexDirection: 'row', borderTopWidth: 1, borderColor: '#EDF0F5', paddingTop: 10, paddingBottom: 11, backgroundColor: '#FFFFFF' }, navItem: { flex: 1, alignItems: 'center', gap: 4 }, navIcon: { width: 54, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, navSelected: { backgroundColor: '#ECF2FF' }, navText: { color: '#929BAB', fontSize: 11, fontWeight: '600' }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, paddingBottom: 70 }, emptyIcon: { width: 76, height: 76, borderRadius: 25, backgroundColor: '#F0F5FF', justifyContent: 'center', alignItems: 'center', marginBottom: 25 }, emptyTitle: { fontSize: 20, fontWeight: '600', color: '#33425C', textAlign: 'center', marginTop: 15 }, emptyBody: { fontSize: 14, color: '#929BAD', textAlign: 'center', lineHeight: 23, marginTop: 10 }, doneCheck: { width: 33, height: 33, backgroundColor: '#ECF3FF', borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginRight: 14 }, doneTitle: { fontSize: 16, lineHeight: 23, color: '#788499', textDecorationLine: 'line-through' }, completedDate: { fontSize: 11, color: '#A0A8B6', marginTop: 5 },
  modal: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#192A4966' }, sheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingHorizontal: 26, paddingBottom: 26, width: '100%', maxWidth: 560, alignSelf: 'center' }, sheetGrip: { width: 35, height: 4, backgroundColor: '#E2E7EF', borderRadius: 3, marginTop: 11, marginBottom: 21, alignSelf: 'center' }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sheetTitle: { color: '#23324C', fontWeight: '700', fontSize: 25, letterSpacing: -0.5 }, sheetSubtitle: { fontSize: 14, color: '#8A96A8', marginBottom: 24 }, input: { borderWidth: 1, borderColor: '#CBD9F5', borderRadius: 14, backgroundColor: '#F8FAFF', padding: 17, fontSize: 16, color: '#23324C' }, sheetNote: { fontSize: 11, color: '#919BAC', marginTop: 12, marginBottom: 24 }, submit: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: blue, borderRadius: 15, minHeight: 54, marginBottom: 12 }, error: { padding: 12, marginHorizontal: 24, marginBottom: 15, backgroundColor: '#FFF3E7', borderRadius: 10 }, errorText: { color: '#955923', fontSize: 12 },
});
